---
title: "simulations"
output: word_document
date: "2024-12-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(purrr)
library(dplyr)
library(stringr)
library(data.table)
library(readr)
library(writexl)
library(stringr)
library(ggplot2)
library(caret)

# original simulations dataset 
long_df <- read.csv("C:/Users/rocpa/OneDrive/Documenti/GitHub/watchyouragent/data_analysis/df_simulations.csv",sep=",")


# later for selection and handling on energy consumption and energy renewal
data_wide <- spread(long_df, output, score) %>% replace(is.na(.), 0) %>% filter(turn %in% c("BR01","BR02","BR03","BR04","BR05")) %>% filter(color != 0) %>% filter(time %in% c(0,1,7,8,14,15,21,22,28,29,35))

data_wide[data_wide$condition == "pre",]$condition <- "First Simulation"
data_wide[data_wide$condition == "post",]$condition <- "Second Simulation"


long_df[long_df$output == "capital",]$output <- "Total Capital"
long_df[long_df$output == "ccr",]$output <- "Contributio Energy Renewal"
long_df[long_df$output == "daysurvived",]$output <- "Farmers Days Alive "
long_df[long_df$output == "energiaaquisita",]$output <- "Energy Consumption"
long_df[long_df$output == "giornaliero",]$output <- "Daily Profit"
long_df[long_df$output == "mucche",]$output <- "Cows Alive"
long_df[long_df$output == "muccheperse",]$output <- "Dead Cows"
long_df[long_df$output == "muccheslider",]$output <- "New Cows"
long_df[long_df$output == "giorno",]$output <- "Day"
long_df[long_df$output == "risenergtot",]$output <- "Natural Resources"
long_df[long_df$condition == "pre",]$condition <- "First Simulation"
long_df[long_df$condition == "post",]$condition <- "Second Simulation"


```


```{r tragedycommons_raw,"Global tragedycommons as plotted during game and energy consumption" echo=FALSE, include = TRUE}

# natural resources lost (including energy renewal + regrowth constant)
long_df %>% filter(turn %in% c("BR02","BR03","BR04","BR05")) %>% filter(output == "Natural Resources") %>%
  filter(time <= 28 & condition == "First Simulation" | condition == "Second Simulation") %>%
  ggplot(aes(x = time, y = score)) +
  geom_line(aes(color = turn), size =  1.2) +
  scale_color_manual("gruppo", values=c("BR02"="darkgreen", "BR03"="darkviolet", "BR04" = "darkorange", "BR05" = "darkblue"),
                     name = "Turn") +
  scale_x_continuous(breaks=seq(0,35,7)) +
  scale_y_continuous(breaks =  seq(0,22050, 4410)) +
facet_wrap(~ factor(condition, levels = c("First Simulation","Second Simulation")), scales = "free") +
  labs(title = NULL, x = "Days", y = "Natural resources",
       subtitle = "Including energy renewal and constant regrowth") +
  theme_bw( ) +
  theme(
    axis.text.x = element_text(angle = 45),legend.position = "bottom"
    )
ggsave(file= "tragedyresources.png",width = 6, height = 4)


# energy consumption raw numbers (energy renewal raw numbers in samescales chunk because decided once a week)
# here reported daily, to show cumulative progress, energy renewal on week

long_df %>% filter(turn %in% c("BR02","BR03","BR04","BR05")) %>% filter(output == "Energy Consumption")  %>%
    filter(time <= 28 & condition == "First Simulation" | condition == "Second Simulation") %>%
  ggplot(aes(x = time, y = score)) +
  geom_line(aes(color = color),linewidth = 1.2) +
  scale_color_manual("gruppo", values=c(azzurro="cyan", blu="blue", rosso = "red",giallo = "orange",rosa = "pink"), name = "Group") +
  scale_x_continuous(breaks=seq(0,35,7)) +
facet_grid(turn ~ factor(condition, levels = c("First Simulation","Second Simulation")), scales = "free") +
  labs(x = "Days", y = "Energy consumption") +
  theme_bw( ) +
  theme(
    axis.text.x = element_text(angle = 45),legend.position = "bottom")
ggsave(file= "images/energyconsumption_raw.png",width = 5, height = 5)


```



```{r samescales,"To put energy renewal and energy consumption on the same scale" ,echo=FALSE, include = FALSE}

# total contributo comune (poi moltiplicato * 10 per diventare energy renewal)
datawide_ccrtot <- data_wide %>% group_by(turn,time,condition,note) %>% summarise(ccrtot = sum(ccr))
# total energia acquisita dei farmers (energy consumption)
datawide_nrgtot <- data_wide %>% group_by(turn,time,condition,note) %>% summarise(nrgtot = sum(energiaaquisita))


# To bring on the same scales energy consumption and energy renewal
# datasets are merged
df <- merge(data_wide, datawide_ccrtot, by = c("turn","time","condition","note"))
df <- merge(df, datawide_nrgtot, by = c("turn","time","condition","note"))

# to select turns and four weeks first simulation
df <- df %>% filter(turn %in% c("BR02","BR03","BR04","BR05")) %>%   filter(condition == "Second Simulation" | condition == "First Simulation" & time <= 28)

# first and last days of the week [0] [1 week 1:7] [2 week 8:14][3 week 15:21][4 week 22:28][5 week 29:35]
# day 1 not necessary here and not included: during first week  they got the capital from harvesting
dft0 <- df %>% group_by(turn,condition,note,color) %>% filter(time == 0) %>% 
  select(time,week,ccr,energiaaquisita,ccrtot,nrgtot)
dft7 <- df %>% group_by(turn,condition,note,color) %>% filter(time == 7) %>% 
  select(time,week,ccr,energiaaquisita,ccrtot,nrgtot)
dft14 <- df %>% group_by(turn,condition,note,color) %>% filter(time == 14) %>%
  select(time,week,ccr,energiaaquisita,ccrtot,nrgtot)
dft21 <- df %>% group_by(turn,condition,note,color) %>% filter(time == 21) %>%
  select(time,week,ccr,energiaaquisita,ccrtot,nrgtot)
dft28 <- df %>% group_by(turn,condition,note,color) %>% filter(time == 28) %>%
  select(time,week,ccr,energiaaquisita,ccrtot,nrgtot)
dft35 <- df %>% group_by(turn,condition,note,color) %>% filter(time == 35) %>%
  select(time,week,ccr,energiaaquisita,ccrtot,nrgtot)
dft8 <- df %>% group_by(turn,condition,note,color) %>% filter(time == 8) %>%
  select(time,week,ccr,energiaaquisita,ccrtot,nrgtot)
dft15 <- df %>% group_by(turn,condition,note,color) %>% filter(time == 15) %>%
  select(time,week,ccr,energiaaquisita,ccrtot,nrgtot)
dft22 <- df %>% group_by(turn,condition,note,color) %>% filter(time == 22) %>%
  select(time,week,ccr,energiaaquisita,ccrtot,nrgtot)
dft29 <- df %>% group_by(turn,condition,note,color) %>% filter(time == 29) %>%
  select(time,week,ccr,energiaaquisita,ccrtot,nrgtot)

#  dataset combined to compute between weeks, last days of week (week.x, week.y) to compute difference energy consumption
dft1w <- merge(dft7,dft0, by = c("turn","condition","note","color"))
dft2w <- merge(dft14,dft7, by = c("turn","condition","note","color"))
dft3w <- merge(dft21,dft14, by = c("turn","condition","note","color"))
dft4w <- merge(dft28,dft21, by = c("turn","condition","note","color"))
dft5w <- merge(dft35,dft28, by = c("turn","condition","note","color"))


# adding first day of the week for contributo comune
dft1w <- merge(dft1w,dft8,by = c("turn","condition","note","color"))
dft2w <- merge(dft2w,dft8,by = c("turn","condition","note","color"))
dft3w <- merge(dft3w,dft15,by = c("turn","condition","note","color"))
dft4w <- merge(dft4w,dft22,by = c("turn","condition","note","color"))
dft5w <- merge(dft5w,dft29,by = c("turn","condition","note","color"))

# final dataset for same scales
dft <- rbind(dft1w,dft2w,dft3w,dft4w,dft5w) 

# same scales
# energy acquired in the week by individual group (end of week.x - end of previous week.y)
dft$nrgacqweek <- (dft$energiaaquisita.x - dft$energiaaquisita.y)
# total energy consumed that week by all groups together (end of week.x - end of previous week.y)
dft$nrgacqtotweek <- (dft$nrgtot.x - dft$nrgtot.y)
# energy renewal from contributo comune invested by individual group (beginning of week, second block)
dft$newnrgweek <- dft$ccr * 10
# total energy renewal of the week by all groups together (beginning of week)
dft$newnrgtotweek <- dft$ccrtot * 10

# computed measures now on the same scale: 
dft$actualnewrng <- dft$newnrgweek - dft$nrgacqweek # energy renewal - energy consumption 
dft$actualnrgacq <-  dft$nrgacqweek - dft$newnrgweek # energy consumption - energy renewal
dft$relatnewnrg <- dft$newnrgweek / dft$nrgacqweek # fraction energy renewal / energy consumption
dft$relatacqnrg <- dft$nrgacqweek / dft$newnrgweek # fraction energy consumption / energy renewal

dft$propnrgacq <- dft$nrgacqweek / dft$nrgacqtotweek # proportion of own energy consumption / energy consumption all groups
dft$propnewnrg <- dft$newnrgweek / dft$newnrgtotweek # proportion of own energy renewal / energy renewal all groups

# fraction energy renewal / energy consumption

dft %>% 
  filter(week.x > 1) %>%
  filter(condition == "First Simulation" & week.x <=  4 | condition == "Second Simulation") %>%
  ggplot(aes(x = time.x, y = relatnewnrg,color = color)) +
  geom_line() +
  geom_point() + 
    scale_color_manual("gruppo", values=c(azzurro="cyan", blu="blue", rosso = "red",giallo = "orange",rosa = "pink"), 
                       name = "Group") +
facet_wrap(~ turn + factor(condition, levels = c("First Simulation","Second Simulation")), scales = "free", ncol =2 ) +
  scale_x_continuous(breaks = seq(2, 6, 1)) +
 labs(y = "Energy renewal / Energy consumption", x = "Weeks") + 
#  guides(color = guide_legend(position =  "bottom")) +
  theme_bw() 
ggsave(file= "images/renewaloverconsumption.png",width = 5, height =6)


# energy renewal (raw number) # example, change y for other observations based on indicators above

dft %>% filter(week.x > 1) %>%
  ggplot(aes(x = time, y = newnrgweek,color = color)) +
  geom_line() +
  geom_point() + 
    scale_color_manual("gruppo", values=c(azzurro="cyan", blu="blue", rosso = "red",giallo = "orange",rosa = "pink"), 
                       name = "Group") +
facet_grid(turn ~ factor(condition, levels = c("First Simulation","Second Simulation")), scales = "free") +
  scale_x_continuous(breaks = seq(8, 29, 7)) +
 labs(y = "Energy renewal", x = "Days") + 
  guides(color = guide_legend(position =  "bottom")) +
  theme_bw() 
ggsave(file= "images/energyrenewal_raw.png",width = 5, height =5)



# proportion of two dimensions compared to other groups: energy renewal and energy consumption

# to make it in long format
# number of columns: 31 propnrgacq (energy consumption), 32 propnewnrg (energy renewal) 
dftlong <- dft %>% filter(week.x > 1) %>%
  pivot_longer(cols = c("propnrgacq","propnewnrg"), names_to = c("proportion"), values_to = "score")  

# energy renewal

dftlong %>%
  filter(proportion == "propnewnrg" ) %>%
  ggplot(aes(x = week.x, y = score,color = color)) +
  geom_line() +
  geom_point() + 
    scale_color_manual("gruppo", values=c(azzurro="cyan", blu="blue", rosso = "red",giallo = "orange",rosa = "pink"),
                       name = "Group") +
#  scale_linetype_manual("proportion", values = c("propnrgacq" = "dashed","propnrenrg" = "solid"), name = "indicator",
#                        labels = c("propnrgacq" = "Energy consumption","propnrenrg" = "Energy renewal")) +
 facet_wrap(~ turn + factor(condition, levels = c("First Simulation","Second Simulation")), scales = "free", ncol = 2) +
  scale_x_continuous(breaks = seq(2, 6, 1)) +
  labs(title = "Contribution to energy renewal", x = "Weeks", y = "proportion", subtitle = "compared to other groups") + 
    guides(linetype = guide_legend(position =  "bottom")) +
  theme_bw() 
ggsave(file= "images/renewal_prop.png",width = 5, height =7)

# energy consumption

dftlong %>%
  filter(proportion == "propnrgacq" ) %>%
  ggplot(aes(x = week.x, y = score,color = color)) +
  geom_line() +
  geom_point() + 
    scale_color_manual("gruppo", values=c(azzurro="cyan", blu="blue", rosso = "red",giallo = "orange",rosa = "pink"),
                       name = "Group") +
#  scale_linetype_manual("proportion", values = c("propnrgacq" = "dashed","propnrenrg" = "solid"), name = "indicator",
#                        labels = c("propnrgacq" = "Energy consumption","propnrenrg" = "Energy renewal")) +
 facet_wrap(~ turn + factor(condition, levels = c("First Simulation","Second Simulation")), scales = "free", ncol = 2) +
  scale_x_continuous(breaks = seq(2, 6, 1)) +
  labs(title = "Contribution to energy consumption", x = "Weeks", y = "proportion", subtitle = "compared to other groups") + 
    guides(linetype = guide_legend(position =  "bottom")) +
  theme_bw() 
ggsave(file= "images/consumption_prop.png",width = 5, height =7)


# individual turn
for (i in c("BR02","BR03","BR04","BR05")) {
  
dftlong %>%
  filter(turn == i) %>%
  ggplot(aes(y=score, x=week.x, color = color, linetype = condition,shape= proportion)) +
  geom_line(aes(linetype = proportion, color = color)) +
  geom_point(aes(color = color, shape = proportion), size = 2) +
     scale_color_manual("gruppo", values=c(azzurro="cyan", blu="blue", rosso = "red",giallo = "orange",rosa = "pink")) +
  scale_shape_manual("proportion", values = c("propnrgacq" = "triangle","propnewnrg" = "square")) + 
  scale_linetype_manual("proportion", values = c("propnrgacq" = "solid","propnewnrg" = "dashed"),  name = "indicator",
                        labels = c("propnrgacq" = "Energy consumption","propnewnrg" = "Energy renewal")) +
   facet_grid(condition ~ color) +
    scale_x_continuous(breaks = seq(2, 6, 1)) +
  scale_y_continuous(limits = c(0,1), breaks = seq(0,1,0.25)) +
  labs(x = "Weeks", y = "Proportion to other groups") +
  theme_bw() +
  ggtitle(paste0("Turn ",i)) +
  guides(linetype = guide_legend(position =  "bottom")) +
  guides(color = "none") +
  guides(shape = "none")
ggsave(file= paste0("images/propturn",i,".png"),width = 8, height = 4)
 
}

# energy consumption from initial pasture energy endowment

datawide_nrgtot$energylost <- 22050 - datawide_nrgtot$nrgtot

datawide_nrgtot %>% filter(turn %in% c("BR02","BR03","BR04","BR05")) %>%
  filter(condition == "Second Simulation" | condition == "First Simulation" & time <= 28) %>%
  ggplot(aes(x = time,y =energylost)) +
  geom_line(aes(color = turn), size =  1.2) +
  scale_y_continuous(breaks=c(-6080, 0, 5000, 10000, 22050)) +
  scale_x_continuous(breaks = seq(0,35,7)) + 
    scale_color_manual("turn", values=c("BR02"="darkgreen", "BR03"="darkviolet", "BR04" = "darkorange", "BR05" = "darkblue"),
                       name = "Turn") +
    facet_grid(turn ~ factor(condition,levels = c("First Simulation","Second Simulation")),
             scales = "free") + 
  labs(x = "Days", y = "Natural resources lost due to farmers activity") + 
  theme_bw()
ggsave(file= "images/energylost.png",width = 5, height =5)

```




```{r decision_proportion (back last slide), echo=FALSE, include = FALSE}

# Proportion of invested capital

# It needs to compute from the capital of last day of the previous week (capital accumulated during the week) and measures of the first day (out of the decision when stopped)

# filtered first days of the week
dftfirst <- data_wide  %>% filter(time %in% c(8,15,22,29)) %>% select(turn,color, condition, time,week,weekday, mucche, muccheslider, muccheperse, capital, ccr)
# filtered last days of the week
dftlast <- data_wide %>% filter(time %in% c(7,14,21,28,35)) %>% select(turn,color, condition, time,week,weekday, mucche, muccheslider, muccheperse, capital, ccr)

# datasets merged
dft_prop <- merge(dftfirst,dftlast,by=c("turn","color", "condition"))

# filtered so to have for each row the first day of the week (.x) and the last day of the previous week (.y)
dft_prop <- dft_prop %>% filter(time.x == 8 & time.y == 7| time.x == 15 & time.y == 14 | time.x == 22 & time.y == 21|
                          time.x ==29 & time.y == 28)

dft_prop <- dft_prop %>% filter(turn != "BR01")
# report new  cows bought.
# cost to buy new mucche: if the number of cows they want in the market (muccheslider.x) is higher than the actual number of cows survived from the week before (mucche.y), then the difference is taken as number of new mucche (equal to mucchenew) and multiplied by costs of buying a new cow (10 Euros). If the number of cows wanted is lower than the actual number of cows survived, then there is no cost associated

dft_prop$mucchenewcost <- ifelse(dft_prop$muccheslider.x > dft_prop$mucche.y, ((dft_prop$muccheslider.x - dft_prop$mucche.y) * 10),0)

# not used,out of boundaries: cost for management of cows in the market: the number of cows wanted time 70 Euros costs for each week, not used
dft_prop$mucchenew <- ifelse(dft_prop$muccheslider.x > dft_prop$mucche.y, dft_prop$muccheslider.x - dft_prop$mucche.y,dft_prop$muccheslider.x)
dft_prop$mucchemngcost <- dft_prop$muccheslider.x * 70

# actual costs computed: cows to buy and investment ccr
dft_prop$totcosts <- (dft_prop$mucchenewcost + dft_prop$ccr.x)
# proportion of buying cows over the own capital from week before (capital.y) at the moment of decision
dft_prop$propbuycow <- dft_prop$mucchenewcost / dft_prop$totcosts
# proportion of investment on contributo comune over the own capital from week before (capital.y) at the moment of decision
dft_prop$propinvccr <- dft_prop$ccr.x / dft_prop$totcosts

## proportion of investment over the own capital from week before at the moment of decision
dft_prop$invested <-  dft_prop$totcosts / dft_prop$capital.y

# check that sum of proportion buy new cows and ccr gives 1
dft_prop$sumpropinvested <- dft_prop$propbuycow + dft_prop$propinvccr
# proportion of saving over the own capital at moment of decision: saving is computed as difference between available capital from the week before (capital.y) and total costs
# dft_prop$propsaving <- (dft_prop$capital.y - dft_prop$totcosts) / dft_prop$capital.y
# to check that the sum of proportions is equal to 1
# dft_prop$totinvest <- dft_prop$propbuycow + dft_prop$propinvccr + dft_prop$propsaving

# long format for aesthetics: the three proportion as score of one variable
long_dft_prop <- dft_prop %>%  pivot_longer(cols = c("propbuycow","propinvccr","invested"), names_to = c("variable"), values_to = "score")  %>% replace(is.na(.), 0)



# capital
long_dft_prop %>%
  filter(turn %in% c("BR02","BR03","BR04","BR05")) %>%
 filter(condition == "First Simulation"  & week.x <= 4 | condition == "Second Simulation") %>%
ggplot(aes(x = week.y, y = capital.y, color = color)) +
geom_line(aes(color = color)) +
geom_point(aes( color = color), size = 2) +
  scale_color_manual(values = c("rosso" = "red","blu" = "blue","azzurro" = "cyan","giallo" = "orange","rosa" = "pink"), name = "Group") +
facet_wrap(~ turn + factor(condition,c("First Simulation","Second Simulation")),
             scales = "free", ncol = 2) +
  scale_x_continuous(breaks = seq(1,5,1)) +
  labs(x = "Weeks",y = "Capital") +
  theme_bw() +
  guides(linetype = guide_legend(position =  "bottom", nrow = 2)) +
  guides(color = guide_legend(position = "bottom")) +
  guides(shape = guide_legend(position =  "bottom", nrow = 2))
ggsave(file= "images/capitalcomparison.png",width = 8, height = 11)

# investment decision

long_dft_prop %>%
  filter(turn %in% c("BR02","BR03","BR04","BR05")) %>%
  filter(variable == "invested")  %>%
 filter(condition == "First Simulation"  & week.x <= 4 | condition == "Second Simulation") %>%
ggplot(aes(x = week.x, y = score, color = color)) +
#geom_line(aes(linetype = variable, color = color)) +
  geom_line(aes(color = color)) +
  geom_point(aes(color = color), size = 2) +
  scale_color_manual(values = c("rosso" = "red","blu" = "blue","azzurro" = "cyan","giallo" = "orange","rosa" = "pink"), name = "Group") +
facet_wrap(~ turn + factor(condition,c("First Simulation","Second Simulation")),
             scales = "free", ncol = 2) +
  labs(x = "Weeks",y = "Capital reinvested") +
   scale_x_continuous(breaks = seq(2,6,1)) +
  theme_bw() +
  guides(linetype = guide_legend(position =  "bottom", nrow = 2)) +
  guides(color = guide_legend(position = "bottom")) +
  guides(shape = guide_legend(position =  "bottom", nrow = 2))
ggsave(file= "images/investedcapital.png",width = 8, height = 11)

# proportion invested in renewal

long_dft_prop %>%
  filter(turn %in% c("BR02","BR03","BR04","BR05")) %>%
  filter(variable == "propinvccr")  %>%
 filter(condition == "First Simulation"  & week.x <= 4 | condition == "Second Simulation") %>%
ggplot(aes(x = week.x, y = score, color = color)) +
#geom_line(aes(linetype = variable, color = color)) +
  geom_line(aes(color = color)) +
  geom_point(aes(color = color), size = 2) +
  scale_color_manual(values = c("rosso" = "red","blu" = "blue","azzurro" = "cyan","giallo" = "orange","rosa" = "pink"), name = "Group") +
facet_wrap(~ turn + factor(condition,c("First Simulation","Second Simulation")),
             scales = "free", ncol = 2) +
  labs(x = "Weeks",title = "Investment on energy renewal over new cows") +
   scale_x_continuous(breaks = seq(2,6,1)) +
  theme_bw() +
  guides(linetype = guide_legend(position =  "bottom", nrow = 2)) +
  guides(color = guide_legend(position = "bottom")) +
  guides(shape = guide_legend(position =  "bottom", nrow = 2))
ggsave(file= "images/proprenewal_investment.png",width = 8, height = 11)

###
# cooperative (ccr) and competitive (buy new cows) over the capital and not the only cost: risk because they can spend more than they have, suggested to avoid


dft_prop$buycow_capital <- dft_prop$mucchenewcost / dft_prop$capital.y
dft_prop$ccr_capital <- dft_prop$ccr.x / dft_prop$capital.y
dft_prop$spare_capital <- (dft_prop$mucchenewcost + dft_prop$ccr.x) / dft_prop$capital.y




```